language: python
# command to install dependencies
install: "make"
jobs:
  include:
    - stage: test
      script:
        - make test
      python: '3.5'
    - stage: test
      script:
        - make test
      python: '3.6'
    - stage: test
      script:
        - make test
      python: '3.7'
      dist: xenial   
